/**
 * Writes dist/_headers, including a Content-Security-Policy whose script hashes
 * are computed from the HTML that was actually built.
 *
 * ── WHY THIS IS GENERATED AND NOT WRITTEN IN netlify.toml ─────────────────
 *
 * The strong form of a CSP has no `unsafe-inline`. To get there, every inline
 * script has to be listed by hash. Hashes hardcoded in a config file are a trap:
 * change one character of the inline script and the hash no longer matches, the
 * browser silently refuses to run it, and the only symptom is a console message
 * on a page that otherwise looks fine.
 *
 * Here the hash is derived from `dist/index.html` after the build, so it cannot
 * disagree with the script it is protecting. `check:prerender` re-derives it
 * independently and fails if the two ever differ.
 *
 * Netlify reads `_headers` from the publish directory with the same semantics
 * as the toml block, so this is a supported place to put them, and it keeps all
 * the security headers in one file rather than split across two.
 *
 *     pnpm generate:headers          (run by build, after vite)
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { inlineScriptHashes } from './lib/csp';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dist = join(root, 'dist');

if (!existsSync(dist)) {
  console.error('\ndist/ not found. Run the build first.\n');
  process.exit(1);
}

const indexHtml = readFileSync(join(dist, 'index.html'), 'utf8');
const scriptHashes = inlineScriptHashes(indexHtml);

/**
 * `style-src` still carries 'unsafe-inline', and honestly so.
 *
 * The app sets inline styles from React for things that are genuinely dynamic:
 * a bar width computed from a ratio, a stagger delay, the drawer's max-height.
 * Hashing those is not possible because they change per render, and nonces are
 * not available on a statically hosted site with no server rendering the page
 * per request.
 *
 * The exposure is real but small: an attacker who can already inject markup
 * could restyle the page. They could not run script, exfiltrate to another
 * origin, or frame it, which are the outcomes that matter.
 */
const csp = [
  "default-src 'self'",
  `script-src 'self' ${scriptHashes.join(' ')} https://us-assets.i.posthog.com`,
  "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
  "font-src 'self' https://fonts.gstatic.com",
  "img-src 'self' data: https:",
  "connect-src 'self' https://us.i.posthog.com https://api.hsforms.com",
  // The booking embed. Without this the iframe is an empty box.
  'frame-src https://calendar.google.com https://calendly.com',
  "form-action 'self' https://api.hsforms.com",
  "base-uri 'self'",
  "object-src 'none'",
  "frame-ancestors 'self'",
  'upgrade-insecure-requests',
].join('; ');

const headers = `# Generated by scripts/generate-headers.ts. Do not edit by hand.
#
# The script-src hashes below are derived from the inline scripts in the built
# index.html. Editing them here would only desynchronise them from the file they
# are protecting.

/*
  Content-Security-Policy: ${csp}
  X-Content-Type-Options: nosniff
  X-Frame-Options: SAMEORIGIN
  Referrer-Policy: strict-origin-when-cross-origin
  Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=(), interest-cohort=()
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Resource-Policy: same-origin
  X-DNS-Prefetch-Control: off

# Hashed filenames, so the content behind a URL never changes and a year is safe.
/assets/*
  Cache-Control: public, max-age=31536000, immutable

# HTML is not hashed. Without revalidation a deploy would never reach anyone who
# had already visited.
/
  Cache-Control: public, max-age=0, must-revalidate

/*.html
  Cache-Control: public, max-age=0, must-revalidate
`;

writeFileSync(join(dist, '_headers'), headers);

console.log(
  `generate:headers — ${scriptHashes.length} inline script hash(es), no 'unsafe-inline' in script-src`,
);
