import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

/**
 * ── rehype-raw WAS REMOVED, AND THAT IS A SECURITY DECISION ───────────────
 *
 * It was configured here, and it does exactly what its name says: it takes raw
 * HTML out of a markdown file and puts it into the DOM unsanitised. React's
 * usual protection does not apply, because the whole purpose of the plugin is
 * to bypass it.
 *
 * That turns every blog post into a stored-XSS vector. Today the posts are
 * written by us, so the risk is theoretical. It stops being theoretical the
 * first time a post is pasted from somewhere, generated by a tool, or accepted
 * from a guest author, and by then nobody remembers this plugin is on.
 *
 * `content/blog` is empty, so removing it costs nothing at all right now, and
 * it takes a dependency out of the tree as well.
 *
 * If raw HTML in posts is genuinely wanted later, the safe shape is
 * rehype-raw followed by rehype-sanitize with an explicit schema. Adding the
 * first without the second is the mistake this is avoiding.
 */

interface BlogRendererProps {
  content: string;
}

const BlogRenderer: React.FC<BlogRendererProps> = ({ content }) => (
  <article className="prose prose-invert max-w-none">
    <ReactMarkdown
      remarkPlugins={[remarkGfm]}
      components={{
        h1: ({ children, ...props }) => (
          <h1 className="text-3xl md:text-4xl font-bold text-[var(--text-primary)] mt-10 mb-4" {...props}>{children}</h1>
        ),
        h2: ({ children, ...props }) => (
          <h2 className="text-2xl md:text-3xl font-bold text-[var(--text-primary)] mt-10 mb-4 pb-2 border-b border-[var(--border-light)]" {...props}>{children}</h2>
        ),
        h3: ({ children, ...props }) => (
          <h3 className="text-xl md:text-2xl font-semibold text-[var(--text-primary)] mt-8 mb-3" {...props}>{children}</h3>
        ),
        p: ({ children, ...props }) => (
          <p className="text-base text-[var(--text-secondary)] leading-relaxed mb-5" {...props}>{children}</p>
        ),
        ul: ({ children, ...props }) => (
          <ul className="list-disc list-outside pl-6 mb-5 space-y-2 text-[var(--text-secondary)]" {...props}>{children}</ul>
        ),
        ol: ({ children, ...props }) => (
          <ol className="list-decimal list-outside pl-6 mb-5 space-y-2 text-[var(--text-secondary)]" {...props}>{children}</ol>
        ),
        li: ({ children, ...props }) => (
          <li className="text-base leading-relaxed" {...props}>{children}</li>
        ),
        blockquote: ({ children, ...props }) => (
          <blockquote className="border-l-4 border-[var(--primary)] pl-5 my-6 italic text-[var(--text-muted)]" {...props}>{children}</blockquote>
        ),
        a: ({ children, href, ...props }) => (
          <a href={href} className="text-[var(--primary)] hover:underline transition-colors" target={href?.startsWith('http') ? '_blank' : undefined} rel={href?.startsWith('http') ? 'noopener noreferrer' : undefined} {...props}>{children}</a>
        ),
        strong: ({ children, ...props }) => (
          <strong className="font-semibold text-[var(--text-primary)]" {...props}>{children}</strong>
        ),
        code: ({ children, className, ...props }) => {
          const isBlock = className?.startsWith('language-');
          if (isBlock) {
            return (
              <code className={`block bg-[var(--bg-elevated)] rounded-[var(--radius-md)] p-4 text-sm overflow-x-auto text-[var(--text-secondary)] ${className}`} {...props}>
                {children}
              </code>
            );
          }
          return (
            <code className="bg-[var(--bg-elevated)] text-[var(--primary)] px-1.5 py-0.5 rounded text-sm font-mono" {...props}>
              {children}
            </code>
          );
        },
        pre: ({ children, ...props }) => (
          <pre className="bg-[var(--bg-elevated)] border border-[var(--border-default)] rounded-[var(--radius-lg)] p-4 my-5 overflow-x-auto" {...props}>{children}</pre>
        ),
        hr: (props) => (
          <hr className="border-[var(--border-light)] my-8" {...props} />
        ),
        table: ({ children, ...props }) => (
          <div className="overflow-x-auto my-5">
            <table className="w-full border-collapse text-sm" {...props}>{children}</table>
          </div>
        ),
        th: ({ children, ...props }) => (
          <th className="text-left p-3 bg-[var(--bg-elevated)] border border-[var(--border-default)] font-semibold text-[var(--text-primary)]" {...props}>{children}</th>
        ),
        td: ({ children, ...props }) => (
          <td className="p-3 border border-[var(--border-default)] text-[var(--text-secondary)]" {...props}>{children}</td>
        ),
      }}
    >
      {content}
    </ReactMarkdown>
  </article>
);

export default BlogRenderer;
